name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  WASMEDGE_VERSION: "0.12.1"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust Target
      run: rustup target add wasm32-wasi
    - name: Build
      run: cargo build --verbose
    - name: Test on WasmEdge
      run: |
        wget https://github.com/WasmEdge/WasmEdge/releases/download/$WASMEDGE_VERSION/WasmEdge-$WASMEDGE_VERSION-manylinux2014_x86_64.tar.gz
        tar -zxf WasmEdge-$WASMEDGE_VERSION-manylinux2014_x86_64.tar.gz
        wget https://github.com/WasmEdge/WasmEdge/releases/download/$WASMEDGE_VERSION/WasmEdge-plugin-wasi_crypto-$WASMEDGE_VERSION-manylinux2014_x86_64.tar.gz
        tar -zxf WasmEdge-plugin-wasi_crypto-$WASMEDGE_VERSION-manylinux2014_x86_64.tar.gz
        mkdir -p WasmEdge-$WASMEDGE_VERSION-Linux/lib/wasmedge/
        cp libwasmedgePluginWasiCrypto.so WasmEdge-$WASMEDGE_VERSION-Linux/lib/wasmedge/
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/WasmEdge-$WASMEDGE_VERSION-Linux/lib
        export PATH=$PATH:$(pwd)/WasmEdge-$WASMEDGE_VERSION-Linux/bin
        export WASMEDGE_PLUGIN_PATH=$(pwd)/WasmEdge-$WASMEDGE_VERSION-Linux/lib/wasmedge
        wasmedge -v
        cargo test --release --verbose
